"""
SHORTS ENGINE STUDIO — Public API v1

Production Task 18: API Access for Developers & Agencies

This module implements the full public REST API including:
- 18.1: REST API endpoints (projects, render, clips, usage)
- 18.2: API key generation, revocation, and listing
- 18.3: Rate limiting per API key based on plan tier
- 18.4: Webhook registration and event delivery
- 18.5: Batch processing endpoint
- 18.6: Swagger UI docs (auto-generated by FastAPI at /docs)
- 18.7: SDK client libraries (Python + Node.js) — future packages
- 18.8: Sandbox environment (test API keys prefixed with "test_")

NOTE (Task 18.6): FastAPI automatically generates interactive API documentation:
  - Swagger UI: available at /docs
  - ReDoc: available at /redoc
  These are served automatically by FastAPI — no additional setup required.

TODO (Task 18.7): SDK Client Libraries
  - Python SDK: publish as `shorts-engine-sdk` on PyPI
  - Node.js SDK: publish as `@shorts-engine/sdk` on npm
  - Both should wrap this REST API with typed methods
  - Auto-generate from OpenAPI spec using openapi-generator

NOTE (Task 18.8): Sandbox Environment
  - Test API keys are prefixed with "test_" (e.g., "test_sk_abc123...")
  - Sandbox keys do not deduct real credits
  - Sandbox renders produce watermarked, low-resolution output
  - Sandbox webhooks include a "sandbox": true field in payload
  - Use test keys during development and integration testing
"""

import hashlib
import hmac
import secrets
import time
import uuid
from datetime import datetime, timezone
from enum import Enum
from typing import Any, Dict, List, Optional

import httpx
from fastapi import APIRouter, Depends, Header, HTTPException, Request, status
from pydantic import BaseModel, Field, HttpUrl



# =============================================================================
# Configuration & Constants
# =============================================================================

API_VERSION = "v1"
API_PREFIX = f"/api/{API_VERSION}"

# Task 18.3: Rate limiting tiers (requests per minute)
RATE_LIMITS = {
    "free": 10,
    "pro": 60,
    "business": 300,
}

# Task 18.8: Sandbox prefix for test API keys
SANDBOX_KEY_PREFIX = "test_"
PRODUCTION_KEY_PREFIX = "sk_"


# =============================================================================
# Pydantic Models — Requests
# =============================================================================

class ProjectCreateRequest(BaseModel):
    """Request body for creating a new project."""
    title: str = Field(..., min_length=1, max_length=200, description="Project title")
    video_url: Optional[str] = Field(None, description="URL to video (YouTube, Vimeo, etc.)")
    config: Optional[Dict[str, Any]] = Field(
        default_factory=dict,
        description="Processing configuration (subtitle_style, aspect_ratio, etc.)"
    )



class RenderRequest(BaseModel):
    """Request body for triggering a render."""
    aspect_ratio: str = Field("9:16", description="Output aspect ratio (9:16, 1:1, 16:9, 4:5)")
    resolution: str = Field("1080p", description="Output resolution (720p, 1080p, 4k)")
    subtitle_style: str = Field("word_highlight", description="Subtitle style template name")
    background_music: Optional[str] = Field(None, description="Background music track ID")
    watermark: bool = Field(False, description="Add watermark overlay")


class APIKeyCreateRequest(BaseModel):
    """Request body for generating a new API key."""
    name: str = Field(..., min_length=1, max_length=100, description="Human-readable key name")
    scopes: List[str] = Field(
        default_factory=lambda: ["projects:read", "projects:write", "render", "usage"],
        description="Permission scopes for this key"
    )


class WebhookRegisterRequest(BaseModel):
    """Request body for registering a webhook."""
    url: HttpUrl = Field(..., description="HTTPS URL to receive webhook events")
    events: List[str] = Field(
        ...,
        description="Events to subscribe to: project.completed, project.failed, credits.low"
    )
    secret: Optional[str] = Field(
        None, description="Optional secret for HMAC signature verification"
    )



class BatchProcessRequest(BaseModel):
    """Request body for batch processing multiple videos."""
    videos: List[Dict[str, Any]] = Field(
        ...,
        min_length=1,
        max_length=50,
        description="List of video objects with 'url' and optional 'title', 'config'"
    )
    default_config: Optional[Dict[str, Any]] = Field(
        default_factory=dict,
        description="Default config applied to all videos (individual configs override)"
    )
    webhook_url: Optional[str] = Field(
        None, description="Webhook URL for batch completion notification"
    )


# =============================================================================
# Pydantic Models — Responses
# =============================================================================

class ProjectResponse(BaseModel):
    """Response for a single project."""
    id: str = Field(..., description="Unique project ID")
    title: str = Field(..., description="Project title")
    status: str = Field(..., description="Status: pending, processing, completed, failed")
    video_url: Optional[str] = Field(None, description="Source video URL")
    config: Dict[str, Any] = Field(default_factory=dict)
    created_at: str = Field(..., description="ISO 8601 creation timestamp")
    updated_at: str = Field(..., description="ISO 8601 last update timestamp")
    clips_count: int = Field(0, description="Number of rendered clips")
    error: Optional[str] = Field(None, description="Error message if status is 'failed'")



class ClipResponse(BaseModel):
    """Response for a single rendered clip."""
    id: str = Field(..., description="Unique clip ID")
    project_id: str = Field(..., description="Parent project ID")
    segment_index: int = Field(..., description="Segment number in sequence")
    title: str = Field(..., description="Generated clip title")
    hook: str = Field("", description="Hook/opening text for the clip")
    start_sec: float = Field(..., description="Start time in source video (seconds)")
    end_sec: float = Field(..., description="End time in source video (seconds)")
    duration: float = Field(..., description="Clip duration in seconds")
    download_url: str = Field(..., description="Signed download URL (expires in 1 hour)")
    thumbnail_url: str = Field(..., description="Thumbnail image URL")
    virality_score: Optional[int] = Field(None, description="Virality score 0-100")
    created_at: str = Field(..., description="ISO 8601 creation timestamp")


class ClipListResponse(BaseModel):
    """Response for listing clips."""
    project_id: str
    clips: List[ClipResponse]
    total: int


class UsageResponse(BaseModel):
    """Response for usage/credits check."""
    user_id: str
    plan: str = Field(..., description="Current plan: free, pro, business")
    credits_remaining: int = Field(..., description="Credits left this billing period")
    credits_total: int = Field(..., description="Total credits for the period")
    credits_used: int = Field(..., description="Credits used this period")
    period_start: str = Field(..., description="Billing period start (ISO 8601)")
    period_end: str = Field(..., description="Billing period end (ISO 8601)")
    rate_limit: int = Field(..., description="Requests per minute for current plan")



class APIKeyResponse(BaseModel):
    """Response after creating an API key (key shown only once)."""
    key_id: str = Field(..., description="Unique key identifier")
    key: str = Field(..., description="The API key (shown only once, store securely!)")
    name: str = Field(..., description="Human-readable key name")
    scopes: List[str] = Field(..., description="Permission scopes")
    created_at: str = Field(..., description="ISO 8601 creation timestamp")
    is_sandbox: bool = Field(False, description="Whether this is a sandbox/test key")


class APIKeyListItem(BaseModel):
    """Response for listing API keys (key value is masked)."""
    key_id: str = Field(..., description="Unique key identifier")
    name: str = Field(..., description="Human-readable key name")
    key_masked: str = Field(..., description="Masked key (e.g., sk_...abc123)")
    scopes: List[str] = Field(..., description="Permission scopes")
    created_at: str = Field(..., description="ISO 8601 creation timestamp")
    last_used_at: Optional[str] = Field(None, description="Last usage timestamp")
    is_sandbox: bool = Field(False, description="Whether this is a sandbox/test key")


class APIKeyListResponse(BaseModel):
    """Response for listing all API keys."""
    keys: List[APIKeyListItem]
    total: int


class WebhookResponse(BaseModel):
    """Response for a registered webhook."""
    id: str = Field(..., description="Webhook registration ID")
    url: str = Field(..., description="Webhook delivery URL")
    events: List[str] = Field(..., description="Subscribed events")
    created_at: str = Field(..., description="ISO 8601 creation timestamp")
    is_active: bool = Field(True, description="Whether webhook is active")



class BatchResponse(BaseModel):
    """Response for batch processing submission."""
    batch_id: str = Field(..., description="Unique batch job ID")
    project_ids: List[str] = Field(..., description="Created project IDs")
    total_videos: int = Field(..., description="Number of videos submitted")
    credits_required: int = Field(..., description="Credits that will be consumed")
    status: str = Field("queued", description="Batch status: queued, processing, completed")
    webhook_url: Optional[str] = Field(None, description="Notification webhook URL")


class ErrorResponse(BaseModel):
    """Standard error response."""
    error: str = Field(..., description="Error type")
    message: str = Field(..., description="Human-readable error description")
    details: Optional[Dict[str, Any]] = Field(None, description="Additional error context")
    request_id: str = Field(..., description="Request ID for support reference")


class RenderTriggerResponse(BaseModel):
    """Response after triggering a render."""
    project_id: str
    status: str = Field("processing", description="Updated project status")
    render_job_id: str = Field(..., description="Render job queue ID")
    estimated_time_seconds: int = Field(..., description="Estimated completion time")
    message: str = Field("Render job queued successfully")


# =============================================================================
# In-Memory Stores (replace with database in production)
# =============================================================================

# Simulated data stores
_api_keys_store: Dict[str, Dict[str, Any]] = {}
_projects_store: Dict[str, Dict[str, Any]] = {}
_webhooks_store: Dict[str, Dict[str, Any]] = {}
_rate_limit_tracker: Dict[str, List[float]] = {}



# =============================================================================
# Authentication & Rate Limiting (Task 18.2, 18.3)
# =============================================================================

def _hash_api_key(key: str) -> str:
    """Hash an API key for secure storage."""
    return hashlib.sha256(key.encode()).hexdigest()


def _mask_api_key(key: str) -> str:
    """Mask an API key for display (show prefix + last 6 chars)."""
    if key.startswith(SANDBOX_KEY_PREFIX):
        return f"test_...{key[-6:]}"
    return f"sk_...{key[-6:]}"


def _is_sandbox_key(key: str) -> bool:
    """Check if an API key is a sandbox/test key (Task 18.8)."""
    return key.startswith(SANDBOX_KEY_PREFIX)


def _generate_api_key(sandbox: bool = False) -> str:
    """Generate a new API key with appropriate prefix."""
    prefix = SANDBOX_KEY_PREFIX if sandbox else PRODUCTION_KEY_PREFIX
    random_part = secrets.token_urlsafe(32)
    return f"{prefix}{random_part}"


def _check_rate_limit(key_id: str, plan: str) -> bool:
    """
    Task 18.3: Check if the API key has exceeded its rate limit.
    Returns True if request is allowed, False if rate-limited.
    """
    limit = RATE_LIMITS.get(plan, RATE_LIMITS["free"])
    now = time.time()
    window_start = now - 60  # 1-minute sliding window

    if key_id not in _rate_limit_tracker:
        _rate_limit_tracker[key_id] = []

    # Remove timestamps outside the window
    _rate_limit_tracker[key_id] = [
        ts for ts in _rate_limit_tracker[key_id] if ts > window_start
    ]

    if len(_rate_limit_tracker[key_id]) >= limit:
        return False

    _rate_limit_tracker[key_id].append(now)
    return True



async def authenticate_api_key(x_api_key: Optional[str] = Header(None)) -> Dict[str, Any]:
    """
    Dependency: Authenticate request via X-API-Key header.
    Returns the user context associated with the key.
    """
    if not x_api_key:
        raise HTTPException(
            status_code=status.HTTP_401_UNAUTHORIZED,
            detail={
                "error": "authentication_required",
                "message": "Missing X-API-Key header. Provide a valid API key.",
                "request_id": str(uuid.uuid4()),
            },
        )

    key_hash = _hash_api_key(x_api_key)
    key_record = None

    for kid, record in _api_keys_store.items():
        if record["key_hash"] == key_hash and record["is_active"]:
            key_record = record
            key_record["key_id"] = kid
            break

    if not key_record:
        raise HTTPException(
            status_code=status.HTTP_401_UNAUTHORIZED,
            detail={
                "error": "invalid_api_key",
                "message": "The provided API key is invalid or has been revoked.",
                "request_id": str(uuid.uuid4()),
            },
        )

    # Task 18.3: Check rate limit
    plan = key_record.get("plan", "free")
    if not _check_rate_limit(key_record["key_id"], plan):
        limit = RATE_LIMITS.get(plan, RATE_LIMITS["free"])
        raise HTTPException(
            status_code=status.HTTP_429_TOO_MANY_REQUESTS,
            detail={
                "error": "rate_limit_exceeded",
                "message": f"Rate limit exceeded. Plan '{plan}' allows {limit} requests/minute.",
                "retry_after_seconds": 60,
                "request_id": str(uuid.uuid4()),
            },
            headers={"Retry-After": "60"},
        )

    # Update last used timestamp
    key_record["last_used_at"] = datetime.now(timezone.utc).isoformat()

    return {
        "user_id": key_record["user_id"],
        "key_id": key_record["key_id"],
        "plan": plan,
        "scopes": key_record.get("scopes", []),
        "is_sandbox": _is_sandbox_key(x_api_key),
    }



# =============================================================================
# Webhook Helper (Task 18.4)
# =============================================================================

async def send_webhook(url: str, event: str, payload: Dict[str, Any]) -> bool:
    """
    Task 18.4: Send a webhook notification to a registered URL.

    Includes HMAC-SHA256 signature in X-Webhook-Signature header if a
    secret is configured for the webhook.

    Args:
        url: The webhook delivery URL.
        event: Event type (project.completed, project.failed, credits.low).
        payload: Event payload data.

    Returns:
        True if delivered successfully, False otherwise.
    """
    webhook_payload = {
        "event": event,
        "timestamp": datetime.now(timezone.utc).isoformat(),
        "data": payload,
        "api_version": API_VERSION,
    }

    # Check if this is a sandbox webhook
    if payload.get("sandbox"):
        webhook_payload["sandbox"] = True

    # Find webhook secret for HMAC signing
    webhook_secret = None
    for wh in _webhooks_store.values():
        if wh["url"] == url:
            webhook_secret = wh.get("secret")
            break

    headers = {
        "Content-Type": "application/json",
        "User-Agent": "ShortsEngine-Webhooks/1.0",
        "X-Webhook-Event": event,
        "X-Webhook-ID": str(uuid.uuid4()),
    }

    # Sign payload if secret is configured
    if webhook_secret:
        import json
        payload_bytes = json.dumps(webhook_payload, sort_keys=True).encode()
        signature = hmac.new(
            webhook_secret.encode(), payload_bytes, hashlib.sha256
        ).hexdigest()
        headers["X-Webhook-Signature"] = f"sha256={signature}"

    try:
        async with httpx.AsyncClient(timeout=30.0) as client:
            response = await client.post(url, json=webhook_payload, headers=headers)
            return response.status_code < 400
    except Exception:
        # Log failure, schedule retry (in production, use exponential backoff)
        return False



# =============================================================================
# Router
# =============================================================================

router = APIRouter(prefix=API_PREFIX, tags=["API v1"])


# =============================================================================
# Task 18.1: Project Endpoints
# =============================================================================

@router.post(
    "/projects",
    response_model=ProjectResponse,
    status_code=status.HTTP_201_CREATED,
    summary="Create a new project",
    description="Create a new project and optionally provide a video URL for processing.",
)
async def create_project(
    body: ProjectCreateRequest,
    auth: Dict[str, Any] = Depends(authenticate_api_key),
):
    """Create a new project with video upload/URL."""
    if "projects:write" not in auth["scopes"]:
        raise HTTPException(
            status_code=status.HTTP_403_FORBIDDEN,
            detail={
                "error": "insufficient_scope",
                "message": "API key does not have 'projects:write' permission.",
                "request_id": str(uuid.uuid4()),
            },
        )

    project_id = str(uuid.uuid4())
    now = datetime.now(timezone.utc).isoformat()

    project = {
        "id": project_id,
        "user_id": auth["user_id"],
        "title": body.title,
        "video_url": body.video_url,
        "config": body.config or {},
        "status": "pending",
        "created_at": now,
        "updated_at": now,
        "clips_count": 0,
        "error": None,
        "is_sandbox": auth["is_sandbox"],
    }

    _projects_store[project_id] = project

    return ProjectResponse(**project)



@router.get(
    "/projects/{project_id}",
    response_model=ProjectResponse,
    summary="Get project status and results",
    description="Retrieve a project's current status, configuration, and results.",
)
async def get_project(
    project_id: str,
    auth: Dict[str, Any] = Depends(authenticate_api_key),
):
    """Get project details by ID."""
    if "projects:read" not in auth["scopes"]:
        raise HTTPException(
            status_code=status.HTTP_403_FORBIDDEN,
            detail={
                "error": "insufficient_scope",
                "message": "API key does not have 'projects:read' permission.",
                "request_id": str(uuid.uuid4()),
            },
        )

    project = _projects_store.get(project_id)
    if not project:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail={
                "error": "project_not_found",
                "message": f"Project '{project_id}' not found.",
                "request_id": str(uuid.uuid4()),
            },
        )

    # Ensure user can only access their own projects
    if project["user_id"] != auth["user_id"]:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail={
                "error": "project_not_found",
                "message": f"Project '{project_id}' not found.",
                "request_id": str(uuid.uuid4()),
            },
        )

    return ProjectResponse(**project)



@router.post(
    "/projects/{project_id}/render",
    response_model=RenderTriggerResponse,
    summary="Trigger rendering for a project",
    description="Start the rendering pipeline for a project. Video must be uploaded first.",
)
async def trigger_render(
    project_id: str,
    body: RenderRequest,
    auth: Dict[str, Any] = Depends(authenticate_api_key),
):
    """Trigger rendering for a project."""
    if "render" not in auth["scopes"]:
        raise HTTPException(
            status_code=status.HTTP_403_FORBIDDEN,
            detail={
                "error": "insufficient_scope",
                "message": "API key does not have 'render' permission.",
                "request_id": str(uuid.uuid4()),
            },
        )

    project = _projects_store.get(project_id)
    if not project or project["user_id"] != auth["user_id"]:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail={
                "error": "project_not_found",
                "message": f"Project '{project_id}' not found.",
                "request_id": str(uuid.uuid4()),
            },
        )

    if project["status"] == "processing":
        raise HTTPException(
            status_code=status.HTTP_409_CONFLICT,
            detail={
                "error": "render_in_progress",
                "message": "This project is already being rendered.",
                "request_id": str(uuid.uuid4()),
            },
        )

    # Update project config with render settings
    project["config"].update({
        "aspect_ratio": body.aspect_ratio,
        "resolution": body.resolution,
        "subtitle_style": body.subtitle_style,
        "background_music": body.background_music,
        "watermark": body.watermark,
    })
    project["status"] = "processing"
    project["updated_at"] = datetime.now(timezone.utc).isoformat()

    render_job_id = str(uuid.uuid4())

    return RenderTriggerResponse(
        project_id=project_id,
        status="processing",
        render_job_id=render_job_id,
        estimated_time_seconds=120,
        message="Render job queued successfully",
    )



@router.get(
    "/projects/{project_id}/clips",
    response_model=ClipListResponse,
    summary="List rendered clips for a project",
    description="Get all rendered clips for a completed project, sorted by virality score.",
)
async def list_clips(
    project_id: str,
    auth: Dict[str, Any] = Depends(authenticate_api_key),
):
    """List all rendered clips for a project."""
    if "projects:read" not in auth["scopes"]:
        raise HTTPException(
            status_code=status.HTTP_403_FORBIDDEN,
            detail={
                "error": "insufficient_scope",
                "message": "API key does not have 'projects:read' permission.",
                "request_id": str(uuid.uuid4()),
            },
        )

    project = _projects_store.get(project_id)
    if not project or project["user_id"] != auth["user_id"]:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail={
                "error": "project_not_found",
                "message": f"Project '{project_id}' not found.",
                "request_id": str(uuid.uuid4()),
            },
        )

    if project["status"] != "completed":
        raise HTTPException(
            status_code=status.HTTP_400_BAD_REQUEST,
            detail={
                "error": "project_not_completed",
                "message": f"Project status is '{project['status']}'. Clips are available only after rendering completes.",
                "request_id": str(uuid.uuid4()),
            },
        )

    # In production, fetch from database
    clips: List[ClipResponse] = []

    return ClipListResponse(
        project_id=project_id,
        clips=clips,
        total=len(clips),
    )



@router.get(
    "/usage",
    response_model=UsageResponse,
    summary="Check credits and usage",
    description="Get current credit balance, plan info, and rate limit for the authenticated user.",
)
async def get_usage(
    auth: Dict[str, Any] = Depends(authenticate_api_key),
):
    """Check credits remaining and usage stats."""
    if "usage" not in auth["scopes"]:
        raise HTTPException(
            status_code=status.HTTP_403_FORBIDDEN,
            detail={
                "error": "insufficient_scope",
                "message": "API key does not have 'usage' permission.",
                "request_id": str(uuid.uuid4()),
            },
        )

    plan = auth["plan"]
    credits_total = {"free": 3, "pro": 30, "business": 9999}.get(plan, 3)
    rate_limit = RATE_LIMITS.get(plan, RATE_LIMITS["free"])

    # In production, fetch from database
    return UsageResponse(
        user_id=auth["user_id"],
        plan=plan,
        credits_remaining=credits_total,
        credits_total=credits_total,
        credits_used=0,
        period_start=datetime.now(timezone.utc).replace(day=1).isoformat(),
        period_end=datetime.now(timezone.utc).isoformat(),
        rate_limit=rate_limit,
    )


# =============================================================================
# Task 18.2: API Key Management Endpoints
# =============================================================================

@router.post(
    "/keys",
    response_model=APIKeyResponse,
    status_code=status.HTTP_201_CREATED,
    summary="Generate a new API key",
    description="Generate a new API key. The key value is returned ONLY in this response — store it securely.",
)
async def create_api_key(
    body: APIKeyCreateRequest,
    auth: Dict[str, Any] = Depends(authenticate_api_key),
):
    """Generate a new API key (returned only once)."""
    # Check key limit (max 10 active keys per user)
    user_keys = [
        k for k in _api_keys_store.values()
        if k["user_id"] == auth["user_id"] and k["is_active"]
    ]
    if len(user_keys) >= 10:
        raise HTTPException(
            status_code=status.HTTP_400_BAD_REQUEST,
            detail={
                "error": "key_limit_reached",
                "message": "Maximum of 10 active API keys per user. Revoke an existing key first.",
                "request_id": str(uuid.uuid4()),
            },
        )

    # Generate key
    is_sandbox = auth["is_sandbox"]
    raw_key = _generate_api_key(sandbox=is_sandbox)
    key_id = str(uuid.uuid4())
    now = datetime.now(timezone.utc).isoformat()

    # Store only the hash
    _api_keys_store[key_id] = {
        "key_hash": _hash_api_key(raw_key),
        "user_id": auth["user_id"],
        "name": body.name,
        "scopes": body.scopes,
        "plan": auth["plan"],
        "is_active": True,
        "is_sandbox": is_sandbox,
        "created_at": now,
        "last_used_at": None,
    }

    return APIKeyResponse(
        key_id=key_id,
        key=raw_key,
        name=body.name,
        scopes=body.scopes,
        created_at=now,
        is_sandbox=is_sandbox,
    )



@router.delete(
    "/keys/{key_id}",
    status_code=status.HTTP_200_OK,
    summary="Revoke an API key",
    description="Permanently revoke an API key. The key will immediately stop working.",
)
async def revoke_api_key(
    key_id: str,
    auth: Dict[str, Any] = Depends(authenticate_api_key),
):
    """Revoke (deactivate) an API key."""
    key_record = _api_keys_store.get(key_id)

    if not key_record or key_record["user_id"] != auth["user_id"]:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail={
                "error": "key_not_found",
                "message": f"API key '{key_id}' not found.",
                "request_id": str(uuid.uuid4()),
            },
        )

    if not key_record["is_active"]:
        raise HTTPException(
            status_code=status.HTTP_400_BAD_REQUEST,
            detail={
                "error": "key_already_revoked",
                "message": "This API key has already been revoked.",
                "request_id": str(uuid.uuid4()),
            },
        )

    key_record["is_active"] = False
    key_record["revoked_at"] = datetime.now(timezone.utc).isoformat()

    return {"message": "API key revoked successfully", "key_id": key_id}


@router.get(
    "/keys",
    response_model=APIKeyListResponse,
    summary="List active API keys",
    description="List all API keys for the authenticated user. Key values are masked for security.",
)
async def list_api_keys(
    auth: Dict[str, Any] = Depends(authenticate_api_key),
):
    """List all active API keys (masked)."""
    keys = []
    for kid, record in _api_keys_store.items():
        if record["user_id"] == auth["user_id"] and record["is_active"]:
            keys.append(APIKeyListItem(
                key_id=kid,
                name=record["name"],
                key_masked=f"{'test_' if record['is_sandbox'] else 'sk_'}...{kid[-6:]}",
                scopes=record["scopes"],
                created_at=record["created_at"],
                last_used_at=record.get("last_used_at"),
                is_sandbox=record["is_sandbox"],
            ))

    return APIKeyListResponse(keys=keys, total=len(keys))



# =============================================================================
# Task 18.4: Webhook Endpoints
# =============================================================================

VALID_WEBHOOK_EVENTS = {"project.completed", "project.failed", "credits.low"}


@router.post(
    "/webhooks",
    response_model=WebhookResponse,
    status_code=status.HTTP_201_CREATED,
    summary="Register a webhook",
    description="Register a URL to receive webhook notifications for specified events.",
)
async def register_webhook(
    body: WebhookRegisterRequest,
    auth: Dict[str, Any] = Depends(authenticate_api_key),
):
    """Register a webhook URL for event notifications."""
    # Validate events
    invalid_events = set(body.events) - VALID_WEBHOOK_EVENTS
    if invalid_events:
        raise HTTPException(
            status_code=status.HTTP_400_BAD_REQUEST,
            detail={
                "error": "invalid_events",
                "message": f"Invalid event types: {list(invalid_events)}. "
                           f"Valid events: {list(VALID_WEBHOOK_EVENTS)}",
                "request_id": str(uuid.uuid4()),
            },
        )

    # Check webhook limit (max 5 per user)
    user_webhooks = [
        w for w in _webhooks_store.values()
        if w["user_id"] == auth["user_id"] and w["is_active"]
    ]
    if len(user_webhooks) >= 5:
        raise HTTPException(
            status_code=status.HTTP_400_BAD_REQUEST,
            detail={
                "error": "webhook_limit_reached",
                "message": "Maximum of 5 active webhooks per user.",
                "request_id": str(uuid.uuid4()),
            },
        )

    webhook_id = str(uuid.uuid4())
    now = datetime.now(timezone.utc).isoformat()

    _webhooks_store[webhook_id] = {
        "id": webhook_id,
        "user_id": auth["user_id"],
        "url": str(body.url),
        "events": body.events,
        "secret": body.secret,
        "is_active": True,
        "created_at": now,
    }

    return WebhookResponse(
        id=webhook_id,
        url=str(body.url),
        events=body.events,
        created_at=now,
        is_active=True,
    )



@router.delete(
    "/webhooks/{webhook_id}",
    status_code=status.HTTP_200_OK,
    summary="Unregister a webhook",
    description="Remove a webhook registration. It will no longer receive events.",
)
async def unregister_webhook(
    webhook_id: str,
    auth: Dict[str, Any] = Depends(authenticate_api_key),
):
    """Unregister (deactivate) a webhook."""
    webhook = _webhooks_store.get(webhook_id)

    if not webhook or webhook["user_id"] != auth["user_id"]:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail={
                "error": "webhook_not_found",
                "message": f"Webhook '{webhook_id}' not found.",
                "request_id": str(uuid.uuid4()),
            },
        )

    if not webhook["is_active"]:
        raise HTTPException(
            status_code=status.HTTP_400_BAD_REQUEST,
            detail={
                "error": "webhook_already_removed",
                "message": "This webhook has already been removed.",
                "request_id": str(uuid.uuid4()),
            },
        )

    webhook["is_active"] = False

    return {"message": "Webhook unregistered successfully", "webhook_id": webhook_id}


# =============================================================================
# Task 18.5: Batch Processing Endpoint
# =============================================================================

@router.post(
    "/batch",
    response_model=BatchResponse,
    status_code=status.HTTP_202_ACCEPTED,
    summary="Submit batch processing job",
    description="Submit multiple video URLs for batch processing. Each video becomes a separate project.",
)
async def batch_process(
    body: BatchProcessRequest,
    auth: Dict[str, Any] = Depends(authenticate_api_key),
):
    """Batch processing: submit multiple videos at once."""
    if "projects:write" not in auth["scopes"]:
        raise HTTPException(
            status_code=status.HTTP_403_FORBIDDEN,
            detail={
                "error": "insufficient_scope",
                "message": "API key does not have 'projects:write' permission.",
                "request_id": str(uuid.uuid4()),
            },
        )

    # Validate all videos have a URL
    for i, video in enumerate(body.videos):
        if "url" not in video:
            raise HTTPException(
                status_code=status.HTTP_400_BAD_REQUEST,
                detail={
                    "error": "invalid_video_entry",
                    "message": f"Video at index {i} is missing required 'url' field.",
                    "request_id": str(uuid.uuid4()),
                },
            )

    credits_required = len(body.videos)
    batch_id = str(uuid.uuid4())
    project_ids = []
    now = datetime.now(timezone.utc).isoformat()

    # Create individual projects for each video
    for video in body.videos:
        project_id = str(uuid.uuid4())
        config = {**(body.default_config or {}), **(video.get("config", {}))}

        project = {
            "id": project_id,
            "user_id": auth["user_id"],
            "title": video.get("title", f"Batch {batch_id[:8]} - Video"),
            "video_url": video["url"],
            "config": config,
            "status": "queued",
            "created_at": now,
            "updated_at": now,
            "clips_count": 0,
            "error": None,
            "is_sandbox": auth["is_sandbox"],
            "batch_id": batch_id,
        }
        _projects_store[project_id] = project
        project_ids.append(project_id)

    return BatchResponse(
        batch_id=batch_id,
        project_ids=project_ids,
        total_videos=len(body.videos),
        credits_required=credits_required,
        status="queued",
        webhook_url=body.webhook_url,
    )
